[versions]
assertj = "3.27.3"  # 2025-01-18
junit   = "5.12.0"  # 2025-02-21
logback = "1.5.17"  # 2025-02-25
lombok  = "1.18.42" # 2025-09 (Java-25+)
slf4j   = "2.0.17"  # 2025-02-25

[libraries]
assertj         = { module = "org.assertj:assertj-core",        version.ref = "assertj" }
junit-jupiter   = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-launcher  = { module = "org.junit.platform:junit-platform-launcher"}  # don't specify version for this guy
logback         = { module = "ch.qos.logback:logback-classic",  version.ref = "logback" }
lombok          = { module = "org.projectlombok:lombok",        version.ref = "lombok" }
slf4j-api       = { module = "org.slf4j:slf4j-api",             version.ref = "slf4j" }

[plugins]
lombok-plugin   = { id = "io.freefair.lombok", version.ref = "lombok" }

